### PR TITLE
Use Borrow and IntoIter to allow slices to be directly added and removed

### LINKED ISSUE #92: Make the add and rm iterator methods use IntoIter and AsRef
That can turn this code

```rust
builder.rm_tag_attributes("a", ["href", "hreflang"].into_iter().cloned())
```

into this

```rust
builder.rm_tag_attributes("a", &["href", "hreflang"])
```

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #92

### CODE REVIEW

**Comment by notriddle** [comment]
The build did pass; if you go into Travis CI yourself you can see that. It didn't report it right because I moved Ammonia to its own organization while it was in the middle of building.

**Comment by lnicola** [comment]
Looks good, but I wonder if `AsRef<str>` wouldn't be more idiomatic. And `&str` would probably be enough in almost all cases, while making the signatures easier to read.

**Comment by notriddle** [comment]
The main reason I used Borrow is that the iterator for `&[&str]` implements `IntoIter<Item=&&str>`, and since our whole motivation was making it work with slices of strings, it didn't make sense to use plain `IntoIter<Item=&str>`.

As for whether to use AsRef or Borrow, I picked Borrow because it was implemented with the ability to go from &&T to &T, which, again, was my whole purpose.

**Comment by notriddle** [comment]
🤦‍♀️ I forgot to actually turn bors back on after transferring this repo. GitHub removes all Apps when you transfer a repository; they didn't used to, I remember running into weird bugs as a result, but I think they switched to just removing all integrations whenever you transfer a repository because it's simpler that way. 🤦‍♂️ 

bors r= @lnicola

**Pull request merged**
